//pbds自带平衡树，用这个非常方便，一下给出示例（Generated by Gemini 3.1 pro)
#include <iostream>
// 1. 引入 pb_ds 的核心头文件
#include <ext/pb_ds/assoc_container.hpp>
#include <ext/pb_ds/tree_policy.hpp>

using namespace std;
using namespace __gnu_pbds; // 必须引入此命名空间

// ==========================================
// 1. 普通平衡树（Set：元素不可重复）模板
// ==========================================
typedef tree<
    int,                                  // Key 类型
    null_type,                            // Value 类型（null_type 表示作为 set 使用）
    less<int>,                            // 比较函数（less 为升序，greater 为降序）
    rb_tree_tag,                          // 底层结构（红黑树）
    tree_order_statistics_node_update     // 开启名次树功能（必须带上这个）
> ordered_set;

// ==========================================
// 2. 多重集平衡树（Multiset：元素可重复）模板
// 竞赛避坑：直接用 less_equal 会导致 erase 行为异常
// 解决方案：通过插入 pair<值, 唯一ID> 强行变回单集
// ==========================================
typedef pair<int, int> pii;
typedef tree<
    pii, 
    null_type, 
    less<pii>, 
    rb_tree_tag, 
    tree_order_statistics_node_update
> ordered_multiset;

int main() {
    // --------------------------------------
    // 基础单集演示
    // --------------------------------------
    ordered_set tr;
    
    // 插入元素 (O(log N))
    tr.insert(10);
    tr.insert(30);
    tr.insert(20);
    tr.insert(50);
    tr.insert(40);

    // 【核心操作 1】order_of_key(x) -> 查询排名
    // 作用：返回严格小于 x 的元素个数（排名从 0 开始）
    int rank = tr.order_of_key(30); 
    cout << "严格小于 30 的元素个数: " << rank << "\n"; // 输出 2

    // 【核心操作 2】find_by_order(k) -> 按排名查询
    // 作用：返回第 k 小元素的迭代器（k 从 0 开始计算）
    auto it = tr.find_by_order(2); 
    cout << "第 2 小（0-indexed）的元素: " << *it << "\n\n"; // 输出 30

    // --------------------------------------
    // 多重集演示 (竞赛实战推荐)
    // --------------------------------------
    ordered_multiset mtr;
    int id_counter = 0; // 全局或局部的唯一时间戳/ID分配器

    // 插入多个相同元素
    mtr.insert({15, ++id_counter});
    mtr.insert({15, ++id_counter});
    mtr.insert({15, ++id_counter});
    mtr.insert({5, ++id_counter});

    // 1. 查询排名：直接查 {x, 0}
    // 因为 second=0 比所有真实插入的同值元素（ID>=1）都小
    cout << "严格小于 15 的元素个数: " << mtr.order_of_key({15, 0}) << "\n"; // 输出 1 (只有 5)

    // 2. 按排名查询：k_th_val = find_by_order(k)->first
    cout << "第 1 小的元素的值: " << mtr.find_by_order(1)->first << "\n"; // 输出 15

    // 3. 安全删除操作：需要先用 lower_bound 找到具体的 pair，然后再 erase
    auto del_it = mtr.lower_bound({15, 0});
    if (del_it != mtr.end() && del_it->first == 15) {
        mtr.erase(del_it); // 只删除了其中一个 15
    }

    // 验证删除后 15 还剩下几个 (原本3个，删了1个，应该剩2个，加上前置的5，总size为3)
    cout << "删除一个 15 后，树的大小: " << mtr.size() << "\n"; // 输出 3

    return 0;
}